### ISSUE TITLE
Implement Export & Import of data

### ISSUE THREAD

**Issue by lunarcloud** [lunarcloud/sta-play-webapp#11]
This would be an IndexedDB importer/exporter.

Would be part of the "Manage Game" dialog outlined in #10 - and would only apply to a single game (and its references) at a time.

- [ ] Import/Export buttons on game management
- [ ] Export game store item and it's references in other stores to single file
- [ ] Import from file to stores

**Comment by moyzone** [comment]
Hi @lunarcloud ,

I noticed you are working on the IndexedDB importer/exporter feature. I have some experience with this and would love to assist if you need any help. Please let me know if there's anything specific I can contribute to.

**Comment by lunarcloud** [comment]
Thanks for the offer @moyzone , but I wanna wait for #10 to be done first.

**Comment by moyzone** [comment]
Oh Ok sure I will contribute in other issues for now then

**Comment by lunarcloud** [comment]
Added in f35e4ea1c9b193b7b77c3591978d67ab5eea3f21 finalized in ec1f950cdd08b8be2f766796001482b3cb87b244
